toggle added, refacto done
WildCodeSchool/2023-03-wns-lamarr-groupe2 pull request #24
Opened 2023-07-07 14:45 UTC by Carlmarion

2023-07-07 14:59 UTC, Hysilie requested changes

2023-07-07 14:59 UTC, Hysilie commented on frontend/package-lock.json
Ca ne doit pas se retrouver dans les PR

2023-07-07 14:59 UTC, Hysilie commented on frontend/src/App.tsx
A retirer de app (import et component) :)

2023-07-07 14:59 UTC, Hysilie commented on frontend/src/components/Toggle.tsx
Bah nice du coup t'as compris vite :D

2023-07-10 15:42 UTC, Hysilie commented on frontend/src/components/Toggle.tsx
Il reste des éléments non souhaités 
```
<<<<<<< HEAD
  styled: "toggle";
=======
  styled: "toggle" | "toggleUntoggled";
>>>>>>> 4141fedc40d3ecc94b7dba715e890055efe486f9
}; 
```

2023-07-10 15:42 UTC, Hysilie commented on frontend/src/index.css
pareil

2023-07-10 15:43 UTC, Hysilie commented on frontend/tailwind.config.js
Du coup laisser custom comme il est et ajouter customsmall

2023-07-10 15:43 UTC, Hysilie commented
Correction à faires + merge la dernière version de dev: )

2023-07-11 07:03 UTC, Carlmarion commented on frontend/src/components/Toggle.tsx
oupsie oui

2023-09-22 10:05 UTC, closed without merging